name: build_dl

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - 
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:

  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Cleaning up
         run: |
           docker rmi `docker images -q`
       - name: Cloning 
         run: |
            #git clone --recurse-submodules  https://github.com/Ayush-Walia/lenovo_z5_dump.git
            #sudo chmod -R 777 lenovo_z5_dump
            python -m pip install --upgrade pip
            pip install gdown
            cd /home/runner/.local/bin
            gdown https://drive.google.com/uc?id=15XzXkaiI1bMs70ZZk7XC0j2WzHbaxyf9  -O havoc3.8.zip
            curl -sL https://git.io/file-transfer | sh
             
       
       - name: up
         run: |
           #7z a -r dl.7z ./lenovo_z5_dump/vendor
           sudo ./transfer wet havoc3.8.zip
           #sudo rm dl.7z      
